### ISSUE TITLE
Fails to display images if the file name contain non Latin characters

### ISSUE THREAD

**Issue by oookubox** [rvalitov/widgetkit-folder-ex#3]
Images are displayed only if the files are named in Latin letters.
Files which consist of Russian letters are displayed as links.

I can give access to administrative part

**Comment by rvalitov** [comment]
Thank you, administrative access will help a lot! Please, send the login/password privately to me to ramilvalitov@gmail.com

**Comment by oookubox** [comment]
sent mail

**Comment by rvalitov** [comment]
Confirmed. This problem happens if file name contains non Latin characters, e.g. accents or Cyrillic characters, e.g.:

```
équipe.jpg
Животное.jpg
Übergabe.jpg
```

This bug came from the original Folder Content plugin.
